GPU: -1
activation: leaky_relu
archi: bigception
bayesian: true
bias: true
data_path: /app/results/runs/bayesian-20260419-01623f
dataset_size: 356798
device: !!python/object/apply:rul_model_factory.cloud_trainer.core.vendor_patch_engine.patched_device
- cpu
fit_context: flipout
guide: normal
last_layer: false
likelihood_scale: 0
lr: 0.0001
model_name: bayesian-20260419-01623f
n_features: 18
num_particles: 1
optimizer: adam
out_path: /app/results/runs/bayesian-20260419-01623f
out_size: 2
pretrain: 10
pretrain_file: /app/results/runs/bayesian-20260419-01623f/bayesian/bayesian-20260419-01623f/lightning_logs/version_0/pretrained_10.pt
prior_loc: 0
prior_scale: 0.4
q_scale: 0.004
test: false
win_length: 30
