GPU: -1
activation: leaky_relu
archi: bigception
bayesian: true
bias: true
data_path: /app/results/runs/bayesian-20260420-0e405c
dataset_size: 356798
device: !!python/object/apply:rul_model_factory.cloud_trainer.core.vendor_patch_engine.patched_device
- cpu
fit_context: flipout
guide: normal
last_layer: false
likelihood_scale: 0
lr: 3.0e-05
model_name: bayesian-20260420-0e405c
n_features: 18
num_particles: 8
optimizer: adam
out_path: /app/results/runs/bayesian-20260420-0e405c
out_size: 2
pretrain: 25
pretrain_file: /app/results/runs/bayesian-20260420-0e405c/bayesian/bayesian-20260420-0e405c/lightning_logs/version_0/pretrained_25.pt
prior_loc: 0
prior_scale: 0.2
q_scale: 0.01
test: false
win_length: 30
